services:
  drawdb:
    restart: always
    image: ${SERVICE_IMAGE_REGISTRY}/whatwewant/drawdb:${SERVICE_DRAWDB_IMAGE_VERSION}
    # ports:
    #   - 0.0.0.0:${SERVICE_DRAWDB_PORT}:8080
      
networks:
  default:
    external: true
    name: compose-ingress
